name: cognitive_training
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rive: ^0.10.3
  rive_splash_screen: ^0.1.1
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  logger: ^1.3.0
  flutter_secure_storage: ^8.0.0
  audioplayers: ^3.0.1
  pausable_timer: ^1.0.0+7
  go_router: ^6.5.0
  auto_size_text: ^3.0.0
  flutter_animate: ^4.1.1+1
  dotted_border: ^2.0.0+3
  tuple: ^2.0.1
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1
  path_provider: ^2.0.15
  flame: ^1.7.3
  flame_audio: ^1.4.1
  flame_rive: ^1.7.1
  flame_bloc: ^1.8.4
  flame_forge2d: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
    #* removed
    # - assets/lottery_game/scene/
    # - assets/lottery_game/scene/feedback/
    # - assets/lottery_game/sound/
    # - assets/lottery_game/sound/chinese/
    # - assets/lottery_game/sound/taiwanese/
    # - assets/poker_game/scene/
    # - assets/poker_game/sound/
    # - assets/poker_game/card/
    - assets/images/home_page/
    - assets/images/ranking_page/
    - assets/images/login_page/
    - assets/images/reward_page/
    - assets/images/lottery_game/
    - assets/images/lottery_game/scene/
    - assets/images/lottery_game/feedback/
    - assets/images/poker_game/
    - assets/images/poker_game/scene/
    - assets/images/poker_game/card/

    #* removed
    # - assets/instruction_record/chinese/lottery_game/
    # - assets/instruction_record/chinese/fishing_game/
    # - assets/instruction_record/chinese/poker_game/
    # - assets/instruction_record/chinese/routing_game/
    # - assets/instruction_record/chinese/tutorial/
    # - assets/instruction_record/taiwanese/lottery_game/
    # - assets/instruction_record/taiwanese/fishing_game/
    # - assets/instruction_record/taiwanese/poker_game/
    # - assets/instruction_record/taiwanese/routing_game/
    # - assets/instruction_record/taiwanese/tutorial/

    # flame part
    - assets/images/
    - assets/images/shared/
    - assets/images/fishing_game/fish/
    - assets/images/fishing_game/garbage/
    - assets/images/fishing_game/ripple/
    - assets/images/fishing_game/rod/
    - assets/images/fishing_game/scene/
    - assets/images/route_planning_game/buildings/
    - assets/images/route_planning_game/hints/
    - assets/images/route_planning_game/scene/
    # for tutorial
    - assets/images/tutorial_mode/
    # audio
    - assets/audio/
    - assets/audio/shared/
    - assets/audio/home_page/chinese/
    - assets/audio/home_page/chinese/tutorial/
    - assets/audio/home_page/taiwanese/
    - assets/audio/home_page/taiwanese/tutorial/
    - assets/audio/lottery_game/sfx/
    - assets/audio/lottery_game/instruction_record/chinese/
    - assets/audio/lottery_game/instruction_record/taiwanese/
    - assets/audio/lottery_game/numbers/chinese/
    - assets/audio/lottery_game/numbers/taiwanese/
    - assets/audio/fishing_game/sfx/
    - assets/audio/fishing_game/instruction_record/chinese/
    - assets/audio/fishing_game/instruction_record/taiwanese/
    - assets/audio/poker_game/sfx/
    - assets/audio/poker_game/instruction_record/chinese/
    - assets/audio/poker_game/instruction_record/taiwanese/
    - assets/audio/route_planning_game/sfx/
    - assets/audio/route_planning_game/instruction_record/chinese/
    - assets/audio/route_planning_game/instruction_record/taiwanese/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. 
  fonts:
    - family: GSR_B
      fonts:
        - asset: assets/ttc/GenSenRounded-B.ttc
    - family: GSR_EL
      fonts:
        - asset: assets/ttc/GenSenRounded-EL.ttc
    - family: GSR_H
      fonts:
        - asset: assets/ttc/GenSenRounded-H.ttc
    - family: GSR_L
      fonts:
        - asset: assets/ttc/GenSenRounded-L.ttc
    - family: GSR_M
      fonts:
        - asset: assets/ttc/GenSenRounded-M.ttc
    - family: GSR_R
      fonts:
        - asset: assets/ttc/GenSenRounded-R.ttc
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
