// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45E5dtEyL8v2FABLnrlJPHz359MdNHYM',
    appId: '1:476169304708:web:0e07ce6a24963a7b5be0d1',
    messagingSenderId: '476169304708',
    projectId: 'cognitive-training-6c8ff',
    authDomain: 'cognitive-training-6c8ff.firebaseapp.com',
    storageBucket: 'cognitive-training-6c8ff.appspot.com',
    measurementId: 'G-LJTW4XQ90W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekOJkydhBLnxZPTs6nIY0yl2zolyF820',
    appId: '1:476169304708:android:1e164aa6db6528365be0d1',
    messagingSenderId: '476169304708',
    projectId: 'cognitive-training-6c8ff',
    storageBucket: 'cognitive-training-6c8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mKSGXWPVqPfGnQTuM0Jr4vh5UY89ST0',
    appId: '1:476169304708:ios:61ccd8f696abd8fe5be0d1',
    messagingSenderId: '476169304708',
    projectId: 'cognitive-training-6c8ff',
    storageBucket: 'cognitive-training-6c8ff.appspot.com',
    iosClientId: '476169304708-vd6gq027stl11m79bri46ut9aa83bsr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cognitiveTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3mKSGXWPVqPfGnQTuM0Jr4vh5UY89ST0',
    appId: '1:476169304708:ios:61ccd8f696abd8fe5be0d1',
    messagingSenderId: '476169304708',
    projectId: 'cognitive-training-6c8ff',
    storageBucket: 'cognitive-training-6c8ff.appspot.com',
    iosClientId: '476169304708-vd6gq027stl11m79bri46ut9aa83bsr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cognitiveTraining',
  );
}
